### ISSUE TITLE
Mimic Broken with 7.0 Update

### ISSUE THREAD

**Issue by Aldr0n** [mbleichner/x4-warehouse-fleets#5]
Hi There!

Just for starters, really really great mod. Unfortunately it seems as the mimic function broke with the big 7.0 update this year. Any chance on a fix? Anything else seems to work just fine, but no fleets can be build using the mimic assignment.

Cheers!

**Comment by mbleichner** [comment]
Thanks, I wasn't aware of that. Haven't played X4 for quite some time. I'll try to have a look at it this weekend.

**Comment by mbleichner** [comment]
The issue should be fixed now. Could you do me a favor and test the version before I push it to Nexus? My savegame is quite dated and contains a lot of other mods - not an ideal testing ground.

[warehousefleets-1.04.zip](https://github.com/user-attachments/files/16321502/warehousefleets-1.04.zip)

**Comment by Aldr0n** [comment]
Sweet! Sure i will test it right away. I am playing currently on the public beta. Gonna report back once i tested it :)

**Comment by mbleichner** [comment]
Did you have time to check if the mimic function works correctly for you now?

**Comment by Aldr0n** [comment]
Hey man, yes i have tested it for at least 3h. Everything seems to work as intendet :)

Thank you so much for the quick fix!

**Comment by mbleichner** [comment]
Alright, thanks a lot. I will publish the update as soon as I get home.

**Comment by Aldr0n** [comment]
Glad to hear and thanks again for the awesome mod. Its a real timesaver :)

**Comment by mbleichner** [comment]
Update on Nexus has been published. Closing this issue. Thanks again for your help :)
